/*
  EduTrack Pro - NodeMCU Attendance System (MySQL PHP Backend)
  Author : Sakshyam Bastakoti & Zenith Kandel
  GitHub : https://github.com/zenithkandel/IoT-RFID-Attendance-System-1
  Date   : 2025-12-02
  
  Description:
    - Reads RFID (MFRC522) card UIDs
    - Shows status on I2C LCD (0x27, 16x2)
    - Sends UID via HTTP POST to PHP API (rfid-checkin.php)
    - PHP backend generates Nepal timestamp and handles check-in/check-out logic
    - WiFiManager for easy WiFi configuration (no hardcoded credentials)
    - Audio-visual feedback (Buzzer, LED, LCD)
    - WiFi-reset button (long press = config portal)
    - Production-ready with error handling
  
  IMPORTANT SETUP INSTRUCTIONS:
    1. Install required libraries:
       - WiFiManager by tzapu
       - MFRC522 by GithubCommunity
       - LiquidCrystal_I2C by Frank de Brabander
    
    2. Update serverHost below with your XAMPP server's IP address:
       - Open Command Prompt and run: ipconfig
       - Look for "IPv4 Address" (e.g., 192.168.1.100)
       - Replace the IP around line 65 (look for serverHost variable)
    
    3. Verify apiEndpoint path matches your project folder location
    
    4. Upload to ESP8266 NodeMCU
    
    5. On first boot, connect to "EduTrackPro" WiFi hotspot
       and configure your network credentials
*/

// ---------- LIBRARIES ----------
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <WiFiManager.h>               // Easy WiFi configuration
#include <SPI.h>
#include <MFRC522.h>                   // RFID library
#include <Wire.h>
#include <LiquidCrystal_I2C.h>         // I2C LCD
#include <ESP8266HTTPClient.h>         // HTTP client for PHP API
#include <WiFiClient.h>                // WiFi client for HTTP requests

// ---------- HARDWARE / SETTINGS ----------
LiquidCrystal_I2C lcd(0x27, 16, 2);    // LCD address 0x27, 16 cols x 2 rows

// If your RFID module uses reset pin, set it; otherwise 255 = not connected
#define RST_PIN   255                 // Not using hardware reset for MFRC522
#define SS_PIN    2                   // D4 (GPIO2) -> SDA for MFRC522 (SS)
#define BUZZER    16                  // D0 (GPIO16)
#define LED       15                  // D8 (GPIO15)
#define BUTTON_PIN 0                  // D3 (GPIO0) - WiFi config / reset button
#define WIFI_LED  LED_BUILTIN         // On-board LED (active LOW on many boards)

// PHP API Configuration (Change this to your server's IP address)
const char* serverHost = "192.168.1.100";  // Replace with your XAMPP server IP
const int   serverPort = 80;               // HTTP port
const char* apiEndpoint = "/projects/iot/IoT-RFID-Attendance-System-/API/rfid-checkin.php";

WiFiClient wifiClient;
HTTPClient http;

// Timing & control
const unsigned long COOLDOWN_DELAY = 1500; // ms between allowed scans
unsigned long lastScanTime = 0;
unsigned long pressStart = 0;
bool readyDisplayed = false;

// RFID object
MFRC522 mfrc522(SS_PIN, RST_PIN);

// ---------- HELPER: small utilities ----------
String byteToHex(byte val) {
  char buf[3];
  sprintf(buf, "%02X", val); // always two hex digits (uppercase)
  return String(buf);
}

// Function to send UID to PHP API
bool sendToAPI(String uid) {
  String url = String("http://") + serverHost + apiEndpoint;
  
  // Build JSON payload with only UID (timestamp will be generated by PHP)
  String payload = "{\"uid\":\"" + uid + "\"}";
  
  http.begin(wifiClient, url);
  http.addHeader("Content-Type", "application/json");
  
  int httpCode = http.POST(payload);
  
  if (httpCode > 0) {
    String response = http.getString();
    Serial.println("HTTP Response code: " + String(httpCode));
    Serial.println("Response: " + response);
    http.end();
    
    // Check if response indicates success (HTTP 200)
    if (httpCode == 200) {
      return true;
    }
  } else {
    Serial.println("HTTP POST failed, error: " + http.errorToString(httpCode));
    http.end();
  }
  
  return false;
}

// ---------- SETUP ----------
void setup() {
  // Serial for debugging
  Serial.begin(115200);
  delay(50);

  // GPIOs
  pinMode(LED, OUTPUT);
  pinMode(BUZZER, OUTPUT);
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(WIFI_LED, OUTPUT);

  digitalWrite(BUZZER, LOW);
  digitalWrite(LED, LOW);
  digitalWrite(WIFI_LED, HIGH); // OFF initially (active-low style)

  // SPI + RFID init
  SPI.begin();
  mfrc522.PCD_Init(); // initialize reader once

  // I2C LCD init (SDA/SCL pins depend on board; Wire.begin uses defaults)
  Wire.begin();            // ESP8266 default SDA = D2(4), SCL = D1(5) on many boards
  lcd.init();
  lcd.backlight();
  lcd.clear();

  // Startup message
  lcd.setCursor(0,0); lcd.print("EduTrack Pro");
  lcd.setCursor(0,1); lcd.print("Initializing...");
  delay(1300);

  // WiFi config (autoConnect opens AP if no saved credentials)
  WiFiManager wm;
  lcd.clear(); lcd.setCursor(0,0); lcd.print("WiFi Setup...");
  if (!wm.autoConnect("EduTrackPro")) {
    // If fails, show message but keep trying (user can power-cycle)
    lcd.clear(); lcd.setCursor(0,0); lcd.print("WiFi Failed");
    lcd.setCursor(0,1); lcd.print("Open AP");
    delay(2000);
  } else {
    lcd.clear(); lcd.setCursor(0,0); lcd.print("WiFi Connected");
    delay(1000);
  }

  // Test connection to PHP API server
  lcd.clear(); lcd.setCursor(0,0); lcd.print("Checking Server");
  
  WiFiClient testClient;
  if (testClient.connect(serverHost, serverPort)) {
    lcd.setCursor(0,1); lcd.print("Server OK");
    testClient.stop();
    delay(900);
  } else {
    lcd.setCursor(0,1); lcd.print("Server Fail");
    delay(900);
  }

  // System ready
  digitalWrite(WIFI_LED, LOW); // ON (active low)
  lcd.clear(); lcd.setCursor(0,0); lcd.print("Scan your Tag");
  readyDisplayed = true;
}

// ---------- MAIN LOOP ----------
void loop() {
  // Check WiFi connection
  if (WiFi.status() != WL_CONNECTED) {
    lcd.clear();
    lcd.setCursor(0,0); lcd.print("WiFi Lost");
    lcd.setCursor(0,1); lcd.print("Reconnecting...");
    digitalWrite(WIFI_LED, HIGH); // OFF (active low)
    delay(1000);
    return;
  }

  // Check long-press for WiFi config portal
  if (digitalRead(BUTTON_PIN) == LOW) {
    if (pressStart == 0) pressStart = millis();
    if (millis() - pressStart > 3000) {
      lcd.clear(); lcd.setCursor(0,0); lcd.print("Config Portal");
      WiFiManager wm;
      wm.startConfigPortal("EduTrackPro-Config");
      // After config portal, restart to reinit modules
      ESP.restart();
    }
  } else {
    pressStart = 0;
  }

  // Ensure the "ready" message displayed once
  if (!readyDisplayed) {
    lcd.clear(); lcd.setCursor(0,0); lcd.print("Scan your Tag");
    readyDisplayed = true;
    digitalWrite(WIFI_LED, LOW); // ON
  }

  // Enforce cooldown
  if (millis() - lastScanTime < COOLDOWN_DELAY) {
    // Allow other tasks in future (non-blocking)
  }

  // Check for new card; return early if none
  if (!mfrc522.PICC_IsNewCardPresent()) return;
  if (!mfrc522.PICC_ReadCardSerial()) return;

  // Busy indicator
  digitalWrite(WIFI_LED, HIGH); // temporarily OFF (active-low)
  digitalWrite(BUZZER, HIGH); delay(80); digitalWrite(BUZZER, LOW);

  // Build compact UID string (no spaces): e.g. "B3:E2:13:2A"
  String uidString = "";
  for (byte i = 0; i < mfrc522.uid.size; i++) {
    uidString += byteToHex(mfrc522.uid.uidByte[i]); // uppercase hex, two chars
    if (i < mfrc522.uid.size - 1) uidString += ":"; // colon separator
  }
  uidString.toUpperCase();
  Serial.println("UID => " + uidString);

  // UI: Sending
  lcd.clear(); lcd.setCursor(0,0); lcd.print("Sending UID...");
  lcd.setCursor(0,1); lcd.print(uidString);

  // Send to PHP API
  bool ok = sendToAPI(uidString);

  // Feedback on result
  if (ok) {
    lcd.clear(); lcd.setCursor(0,0); lcd.print("Success!");
    lcd.setCursor(0,1); lcd.print(uidString);
    // Double beep for success
    tone(BUZZER, 1200, 150); delay(160);
    tone(BUZZER, 1200, 150); delay(160);
    digitalWrite(LED, HIGH); delay(200); digitalWrite(LED, LOW);
  } else {
    lcd.clear(); lcd.setCursor(0,0); lcd.print("Failed!");
    lcd.setCursor(0,1); lcd.print("Try Again");
    // Single long beep for failure
    tone(BUZZER, 600, 300); delay(320);
  }

  // short pause so user can read
  delay(800);

  // Reset display and ready flag
  lcd.clear(); lcd.setCursor(0,0); lcd.print("Scan your Tag");
  readyDisplayed = true;
  lastScanTime = millis();

  // Halt the tag and stop crypto
  mfrc522.PICC_HaltA();
  mfrc522.PCD_StopCrypto1();

  // Ensure WIFI_LED returns to ON (active low)
  digitalWrite(WIFI_LED, LOW);
}
//------------coded By Sakshyam Bastakoti